# Site settings
title: 数据挖掘@北京理工大学
email: simontangbit@bit.edu.cn
description: "数据挖掘的相关材料"
baseurl: ""
url: "http://bitdm.github.io"
#twitter_username: cs231n
# github_username:  bitdm

# Build settings
markdown: redcarpet
permalink: pretty
